open source/Django/day2/leb/bookstore/books/urls.py
from django.urls import path
from . import views

app_name='books'

urlpatterns = [
    # path("<name>", index , name='index')
    # path("<int:age>", index , name='index')
    # path("<int:age>", index , name='index')
    path("",views.index,name='index'),
    # path("<int:book_id>", views.single , name='single'),
    # path("<int:author_id>", views.author , name='author')
     path("book/<int:book_id>/", views.single, name='single'),
    path("author/<int:author_id>/", views.author, name='author'),
]

open source/Django/day2/leb/bookstore/bookstore/urls.py
from django.contrib import admin
from django.urls import path ,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path("books/", include("books.urls",namespace='books')) 
]

open source/Django/day2/leb/bookstore/books/models.py
from django.db import models


class Author(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Books(models.Model):
    name = models.CharField(max_length=255)
    publish_date = models.DateField()
    add_to_site_at = models.DateField(auto_now_add=True)
    author = models.ForeignKey(
        Author, on_delete=models.CASCADE, related_name='books')
    price = models.DecimalField(max_digits=6, decimal_places=2)
    appropriate = models.CharField(max_length=10, choices=[
        ('under_8', 'Under 8'),
        ('8_15', '8-15'),
        ('adults', 'Adults'),
    ])

    def __str__(self):
        return self.name

open source/Django/day2/leb/bookstore/books/views.py
from django.shortcuts import render
from django.http import HttpResponse
import os
import json
from django.conf import settings
from . import models

def index(request):
    # return HttpResponse(f"hello world")
    # return HttpResponse(f"hello world {name * 5}")
    # return HttpResponse(f"hello world {age * 5}")

    # books_data = read_file('books.json')  # Load from file
    books_data = models.Books.objects.all()
    context = {
        "books": books_data
    }
    # go to sitting ->INSTALLED_APPS--> write books.apps.BooksConfig
    return render(request, 'books/index.html', context)


def single(request, book_id):
    context = {}
    # books_data = read_file('books.json')
    # for book in books_data:
    #     if book['id'] == book_id:
    #         context["book"]=book
    #         return render(request, 'books/single.html',context)
    book = models.Books.objects.get(pk=book_id)
    context={
        'book': book
    }
    return render(request, 'books/single.html',context)


def author(request, author_id):
    context = {}
    author = models.Author.objects.get(pk=author_id)
    context={
        'author': author,
        'books' : author.books.all()
    }
    return render(request, 'books/author.html',context)



# ---------helper methods----
# def read_file(file_name):
#     # json_path = os.path.join(settings.BASE_DIR, file_name)
#     json_path = os.path.join(settings.BASE_DIR, 'books', 'static', 'books', 'files', file_name)
#     with open(json_path, 'r') as file:
#         books = json.load(file)
#     return books

open source/Django/day2/leb/bookstore/books/templates/books/author.html
{% extends 'books/base.html' %}
{% load static %}

{% block 'content' %}
<main>
    <div class="container my-5">
        <h2 class="text-center mb-4">Author: {{ author.name }}</h2>
        <h3>List Books :</h3>
        <div class="d-flex justify-content-evenly flex-wrap gap-3">
            {% for book in books %}
            <div class="card m-3 border-dark" style="width: 18rem;">
                <img src="{% static 'books/images/2.png' %}" class="card-img-top" alt="book image">
                <div class="card-body">
                    <h5 class="card-title text-center">{{ book.name }}</h5>
                    <hr>
                    <h6 class="card-text">Publish date: {{ book.publish_date }}</h6>
                    <h6 class="card-text">Price: {{ book.price }}$</h6>
                    <a href="{% url 'books:single' book.id %}" class="btn btn-info mt-3 w-100">See All Details</a>
                </div>
            </div>
            {% empty %}
            <p class="text-center">No books found for this author.</p>
            {% endfor %}
        </div>
    </div>
</main>
{% endblock %}

open source/Django/day2/leb/bookstore/books/templates/books/base.html
<!-- {% load static %} -->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block 'title' %}Welcome To Our Store{% endblock%}</title>
    {% block 'css' %}
        <link rel="stylesheet" href="{% static 'books/css/style.css' %}">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    {% endblock %}
</head>

<body>
    <header>
        <h1 class="text-center m-5">Hello in our book store</h1>
    </header>
    <hr>
    {% block 'content' %}{% endblock %}

    <footer>
        <h1 class="text-center m-5">Footer : Hello in our book store</h1>
    </footer>
</body>

</html>

open source/Django/day2/leb/bookstore/books/templates/books/index.html
{% extends 'books/base.html'%}
{% load static %}

{% block 'content' %}
<main>
    <div class="d-flex justify-content-evenly flex-wrap gap-3">
        {% for book in books %}
        <!-- <li>
                <a href="{% url 'books:single' book.id %}">{{book.name}}</a>
            </li> -->
        <div class="card m-5 border-dark" style="width: 18rem;">
            <!-- <img src="{% static book.image %}" class="card-img-top" alt="..."> -->
            <img src="{% static 'books/images/2.png' %}" alt="books">
            <div class="card-body">
                <h5 class="book-name text-center">{{book.name}}</h5>
                <hr>
                <h6 class="card-text">Publish date : {{book.publish_date}}</h6>
                <h6 class="card-text">Add to site at : {{book.add_to_site_at}}</h6>
                <hr>
                <a href="{% url 'books:author' book.author.id %}" class="btn btn-info">Author : {{book.author}}</a>
                <hr>
                <h6 class="card-text">Price : {{book.price}}$</h6>
                <hr>
                <h6 class="card-text">appropriate : {{book.appropriate}}</h6>
                <hr>
                <a href="{% url 'books:single' book.id %}" class="btn btn-info">See All details</a>
            </div>
        </div>
        {% endfor %}
    </div>
    <!-- <img src="{% static 'books/images/1.jpg' %}" alt="girl image"> -->
</main>
{% endblock %}

open source/Django/day2/leb/bookstore/books/templates/books/single.html
{% extends 'books/base.html'%}
{% load static %}

{% block 'content' %}
<div class="card mb-3 p-5 border-dark w-75 mx-auto vh-80">
  <!-- <img src="{% static book.image %}" class="card-img-top" style="height: 90%;" alt="..."> -->
  <div class="card-body">
    <h5 class="book-name text-center">{{book.name}}</h5>
    <hr>
    <div class="d-flex justify-content-evenly">
 <h6 class="card-text">Publish date : {{book.publish_date}}</h6>
    <h6 class="card-text">Add to site at : {{book.add_to_site_at}}</h6>
    </div>
   
    <hr>
    <h6 class="card-text text-center">Author : {{book.author}}</h6>
    <hr>
    <h6 class="card-text text-center">Price : {{book.price}}$</h6>
    <hr>
    <h6 class="card-text text-center">appropriate : {{book.appropriate}}</h6>
  </div>
</div>
{% endblock %}